services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/app
      - ./server/test.db:/app/test.db  
    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/app

