services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/app
      - ./server/test.db:/app/test.db  # Mount SQLite database file
    ports:
      - "8000:8000"
    # Removed the dependency from client

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/app
    # Removed the dependency on server here

